"""
Layer 4 - Risk Report Generator
Combines RAG answers + anomaly detection results into a PDF report.
Uses fpdf2 to generate a clean, professional risk summary document.
"""

import pandas as pd
from fpdf import FPDF
from datetime import datetime
from pathlib import Path


class RiskReport(FPDF):
    """Custom PDF class with header and footer."""

    def header(self):
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(30, 60, 114)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, "AI-Powered Audit Risk Intelligence Report", align="C", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by Audit Risk AI | Page {self.page_no()}", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_fill_color(240, 240, 245)
        self.set_text_color(30, 60, 114)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT", fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 6, text)
        self.ln(2)

    def risk_badge(self, level: str):
        colors = {
            "HIGH": (220, 50, 50),
            "MEDIUM": (230, 140, 20),
            "LOW": (40, 160, 80)
        }
        r, g, b = colors.get(level, (100, 100, 100))
        self.set_fill_color(r, g, b)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 9)
        self.cell(25, 7, level, align="C", fill=True)
        self.set_text_color(0, 0, 0)


def generate_report(
    rag_results: list[dict],
    anomaly_summary: pd.DataFrame,
    anomaly_tables: list[dict],
    output_path: str = "data/processed/risk_report.pdf"
) -> str:
    """
    Generate the full PDF risk report.

    Args:
        rag_results: List of {query, answer, sources} dicts from RAG engine
        anomaly_summary: Summary DataFrame from anomaly detection
        anomaly_tables: Full anomaly results list
        output_path: Where to save the PDF

    Returns:
        Path to the generated PDF
    """
    pdf = RiskReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # --- Cover info ---
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Report Date: {datetime.now().strftime('%d %B %Y, %H:%M')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, "Powered by: Groq LLaMA3 + ChromaDB + Isolation Forest", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # --- Section 1: Executive Summary ---
    pdf.section_title("1. Executive Summary")
    total_anomalies = anomaly_summary["IF Anomalies"].sum() if not anomaly_summary.empty else 0
    high_risk = len(anomaly_summary[anomaly_summary["Risk Level"] == "HIGH"]) if not anomaly_summary.empty else 0

    summary_text = (
        f"This report presents findings from an automated AI audit analysis. "
        f"A total of {total_anomalies} anomalies were detected across {len(anomaly_summary)} financial table(s). "
        f"{high_risk} table(s) were classified as HIGH RISK based on anomaly density. "
        f"The RAG-based Q&A system analysed {len(rag_results)} audit question(s) against the uploaded documents."
    )
    pdf.body_text(summary_text)

    # --- Section 2: Anomaly Detection Results ---
    pdf.section_title("2. Anomaly Detection Results")

    if not anomaly_summary.empty:
        # Table header
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(220, 220, 230)
        col_widths = [50, 30, 25, 30, 30, 25]
        headers = ["Source", "Sheet", "Rows", "IF Anomalies", "Z-Score Flags", "Risk"]
        for i, h in enumerate(headers):
            pdf.cell(col_widths[i], 8, h, border=1, fill=True)
        pdf.ln()

        # Table rows
        pdf.set_font("Helvetica", "", 9)
        for _, row in anomaly_summary.iterrows():
            pdf.cell(col_widths[0], 7, str(row["Source"])[:20], border=1)
            pdf.cell(col_widths[1], 7, str(row["Sheet"])[:12], border=1)
            pdf.cell(col_widths[2], 7, str(row["Total Rows"]), border=1, align="C")
            pdf.cell(col_widths[3], 7, str(row["IF Anomalies"]), border=1, align="C")
            pdf.cell(col_widths[4], 7, str(row["Z-Score Flags"]), border=1, align="C")
            pdf.cell(col_widths[5], 7, "", border=1)
            x, y = pdf.get_x() - col_widths[5], pdf.get_y()
            pdf.set_xy(x + 2, y + 1)
            pdf.risk_badge(str(row["Risk Level"]))
            pdf.set_xy(pdf.l_margin, y + 7)
        pdf.ln(4)

        # Show top flagged rows per table
        for table in anomaly_tables:
            flagged = table["dataframe"][table["dataframe"]["is_anomaly"] == True]
            if not flagged.empty:
                pdf.set_font("Helvetica", "B", 10)
                pdf.cell(0, 7, f"Flagged rows in: {table['source']} ({table['sheet']})", new_x="LMARGIN", new_y="NEXT")
                numeric_cols = flagged.select_dtypes(include=["number"]).columns.tolist()
                display_cols = [c for c in numeric_cols if c not in ["anomaly_score", "max_zscore"]][:4]
                if display_cols:
                    sample = flagged[display_cols + ["anomaly_score"]].head(5)
                    pdf.set_font("Helvetica", "", 8)
                    pdf.body_text(sample.to_string(index=True))
    else:
        pdf.body_text("No financial tables were provided for anomaly detection.")

    # --- Section 3: RAG Q&A Analysis ---
    pdf.add_page()
    pdf.section_title("3. Document Q&A Analysis (RAG)")
    pdf.body_text(
        "The following questions were automatically asked against the uploaded audit documents "
        "using a Retrieval-Augmented Generation (RAG) pipeline with Groq LLaMA3."
    )

    for i, result in enumerate(rag_results, 1):
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_fill_color(245, 245, 250)
        pdf.cell(0, 7, f"Q{i}: {result['query']}", new_x="LMARGIN", new_y="NEXT", fill=True)
        pdf.set_font("Helvetica", "", 10)
        answer_preview = result["answer"][:600] + ("..." if len(result["answer"]) > 600 else "")
        answer_preview = answer_preview.encode("latin-1", errors="replace").decode("latin-1")
        pdf.multi_cell(0, 6, answer_preview)
        if result.get("sources"):
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(0, 5, "Sources: " + ", ".join(result["sources"][:3]), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
        pdf.ln(4)

    # --- Section 4: Recommendations ---
    pdf.section_title("4. Recommendations")
    recommendations = [
        "1. Investigate all rows flagged as HIGH RISK anomalies with the finance team.",
        "2. Cross-reference anomalous transactions with supporting documentation.",
        "3. Review revenue and expense entries that exceed 3 standard deviations from the mean.",
        "4. Schedule follow-up audit for any document sections where the RAG system returned 'Not found'.",
        "5. Re-run this analysis monthly to track trends over time.",
    ]
    for rec in recommendations:
        pdf.body_text(rec)

    # Save
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    pdf.output(output_path)
    print(f"[Report] PDF saved to: {output_path}")
    return output_path


if __name__ == "__main__":
    # Test with dummy data
    dummy_rag = [
        {
            "query": "What are the key risk indicators?",
            "answer": "The document highlights elevated accounts receivable as a primary risk factor, alongside a 23% increase in operating expenses without corresponding revenue growth.",
            "sources": ["annual_report.pdf (page 4)"]
        }
    ]
    dummy_summary = pd.DataFrame([{
        "Source": "financials.xlsx",
        "Sheet": "Q3",
        "Total Rows": 100,
        "IF Anomalies": 7,
        "Z-Score Flags": 3,
        "Risk Level": "HIGH"
    }])
    generate_report(dummy_rag, dummy_summary, [], "data/processed/test_report.pdf")
