import { useState } from "react";
import { generateReport } from "../api";
import { FileText, Download, CheckCircle, Loader } from "lucide-react";
import toast from "react-hot-toast";

export default function ReportPage({ health }) {
  const [loading, setLoading] = useState(false);
  const [done, setDone]       = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const res = await generateReport();
      const url = window.URL.createObjectURL(new Blob([res.data], { type: "application/pdf" }));
      const a = document.createElement("a");
      a.href = url;
      a.download = "audit_risk_report.pdf";
      a.click();
      window.URL.revokeObjectURL(url);
      setDone(true);
      toast.success("Report downloaded!");
    } catch (e) {
      toast.error(e.response?.data?.detail || "Could not generate report");
    }
    setLoading(false);
  };

  const ready = health && (health.rag_history_count > 0 || health.anomaly_results_count > 0);

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
      <div style={{ animation: "fadeUp 0.5s ease forwards" }}>
        <h1 style={{ fontSize: 28, fontWeight: 800, color: "var(--text-primary)", marginBottom: 4 }}>Risk Report</h1>
        <p style={{ color: "var(--text-muted)", fontSize: 15 }}>Generate a complete PDF audit report from your session data</p>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>
        {/* Generate card */}
        <div className="card" style={{ padding: 32, display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center", gap: 20 }}>
          <div style={{ width: 72, height: 72, borderRadius: 20, background: "var(--accent-light)", display: "flex", alignItems: "center", justifyContent: "center" }}>
            {done
              ? <CheckCircle size={32} style={{ color: "var(--success)" }} />
              : <FileText size={32} style={{ color: "var(--accent)" }} />
            }
          </div>
          <div>
            <h2 style={{ fontSize: 20, fontWeight: 800, fontFamily: "Syne", color: "var(--text-primary)", marginBottom: 8 }}>
              {done ? "Report Ready!" : "Generate PDF Report"}
            </h2>
            <p style={{ fontSize: 14, color: "var(--text-muted)", lineHeight: 1.6, maxWidth: 300 }}>
              {done
                ? "Your report has been downloaded. Click again to regenerate with the latest data."
                : ready
                  ? "Your session data is ready. Click below to generate and download the full audit risk report."
                  : "Upload documents and ask at least one question before generating a report."
              }
            </p>
          </div>
          <button
            className="btn btn-primary"
            style={{ padding: "14px 32px", fontSize: 15 }}
            onClick={handleGenerate}
            disabled={loading || !ready}
          >
            {loading
              ? <><Loader size={16} style={{ animation: "spin 1s linear infinite" }} /> Generating...</>
              : <><Download size={16} /> {done ? "Download Again" : "Generate & Download"}</>
            }
          </button>
          {!ready && (
            <p style={{ fontSize: 12, color: "var(--text-muted)" }}>
              Upload documents first →{" "}
              <a href="/" style={{ color: "var(--accent)", textDecoration: "none" }}>Go to Overview</a>
            </p>
          )}
        </div>

        {/* What's included */}
        <div className="card" style={{ padding: 28 }}>
          <h3 style={{ fontSize: 16, fontWeight: 700, fontFamily: "Syne", color: "var(--text-primary)", marginBottom: 20 }}>
            What's included in the report
          </h3>
          {[
            { n: "01", t: "Executive Summary",    d: "High-level overview of total anomalies found and risk classification across all uploaded tables" },
            { n: "02", t: "Anomaly Detection",    d: "Detailed tables showing all flagged rows, their anomaly scores, and risk levels per data source" },
            { n: "03", t: "Document Q&A Analysis",d: "All questions asked and answers generated by the RAG engine, with source citations" },
            { n: "04", t: "Recommendations",      d: "Auto-generated action items based on the findings, ready to present to a client" },
          ].map(({ n, t, d }) => (
            <div key={n} style={{ display: "flex", gap: 14, marginBottom: 18 }}>
              <div style={{ width: 32, height: 32, borderRadius: 8, background: "var(--accent-light)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                <span style={{ fontSize: 11, fontWeight: 800, fontFamily: "Syne", color: "var(--accent)" }}>{n}</span>
              </div>
              <div>
                <div style={{ fontSize: 14, fontWeight: 600, color: "var(--text-primary)", fontFamily: "Syne", marginBottom: 4 }}>{t}</div>
                <div style={{ fontSize: 12, color: "var(--text-muted)", lineHeight: 1.6 }}>{d}</div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Session snapshot */}
      {health && (
        <div className="card" style={{ padding: 20 }}>
          <h3 style={{ fontSize: 14, fontWeight: 700, fontFamily: "Syne", color: "var(--text-secondary)", letterSpacing: "0.05em", textTransform: "uppercase", marginBottom: 14 }}>
            Current Session
          </h3>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 16 }}>
            {[
              { label: "Vector Store",    value: health.vector_store_ready ? "Ready" : "Empty",  ok: health.vector_store_ready },
              { label: "Questions Asked", value: health.rag_history_count,                        ok: health.rag_history_count > 0 },
              { label: "Tables Loaded",  value: health.anomaly_results_count,                    ok: health.anomaly_results_count > 0 },
            ].map(({ label, value, ok }) => (
              <div key={label} style={{ textAlign: "center", padding: "16px 20px", background: "var(--bg-tertiary)", borderRadius: 12, border: "1px solid var(--border)" }}>
                <div style={{ fontSize: 28, fontWeight: 800, fontFamily: "Syne", color: ok ? "var(--accent)" : "var(--text-muted)", marginBottom: 6 }}>
                  {String(value)}
                </div>
                <div style={{ fontSize: 12, color: "var(--text-muted)" }}>{label}</div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
